# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='message',
            field=models.CharField(default=b'', max_length=300),
        ),
        migrations.AlterField(
            model_name='greeting',
            name='title',
            field=models.CharField(default=b'', max_length=300),
        ),
    ]
